---

##########################################################
# AWS Configuration file for NodeJS Deploy GitHub Action #
#                                                        #
# NOTE: This file holds the variables needed             #
# to configure the GitHub Deploy NodeJS                  #
# on AWS Serverless                                      #
#                                                        #
# This file needs to be in the location:                 #
# - .github/aws-config.yml                               #
# in your repository to be parsed at run time            #
##########################################################

########################################
# AWS S3 Bucket for package and deploy #
########################################
# NOTE: This bucket must exist before the GitHub Action
s3_bucket:

##################################
# AWS Cloud Formation Stack name #
##################################
# NOTE: Defaults to "mystack" if left empty
aws_stack_name: mystack

####################
# AWS SAM Template #
####################
# NOTE: This is the AWS SAM template.yml file that we need to deploy
# Pathing is from root of repository:
# Example:
# if file is called `template.yml` and is in the root of repository
# under the '.github' folder:
# sam_template: .github/template.yml
sam_template:

################################
# region for connection to AWS #
################################
# Default region is: us-west-2
# if not provided below
region: us-west-2
