#################################
# GitHub Dependabot Config info #
#################################
version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for js with npm
  - package-ecosystem: "npm"
    directory: "/dependencies"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for ruby with bundler
  - package-ecosystem: "bundler"
    directory: "/dependencies"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Maintain dependencies for python with pip
  - package-ecosystem: "pip"
    directory: "/dependencies"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

