descriptor_id: OPENAPI
descriptor_type: tooling_format
file_extensions:
  - ".yml"
  - ".yaml"
  - ".json"
file_contains:
  - '"openapi":'
  - '"swagger":'
  - 'openapi:'
  - 'swagger:'
linters:
  # Spectral
  - linter_name: spectral
    linter_url: https://github.com/stoplightio/spectral
    linter_banner_image_url: https://github.com/stoplightio/spectral/raw/develop/docs/img/spectral-banner.png
    linter_rules_configuration_url: https://meta.stoplight.io/docs/spectral/docs/getting-started/3-rulesets.md
    config_file_name: .openapirc.yml
    cli_lint_extra_args:
      - "lint"
    cli_config_arg_name: "-r"
    examples:
      - "spectral lint myfile.yml"
      - "spectral lint -r .openapirc.yml myfile.yml"
    install:
      npm:
        - "@stoplight/spectral"
