---
##########################
##########################
## Cleanup Docker Image ##
##########################
##########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

########################################
# Run job when PR is merged and closed #
########################################

on:
  pull_request:
    types: [closed]

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Cleanup Docker Image - DEV
    # Set the agent to run on
    runs-on: ubuntu-latest
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2
        run: git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*

      ######################
      # Run Removal script #
      ######################
      - name: Remove old image from DockerHub
        env:
          # Set the Env Vars
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_REPO: admiralawkbar/super-linter
        shell: bash
        run: .automation/cleanup-docker.sh
