name: Update Deps - NPM
on:
  schedule:
    # Sunday at 5:00pm
    - cron: "0 17 * * 0"
  workflow_dispatch:
jobs:
  update:
    name: Update NPM Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/scripts/update-npm.sh
        env:
          id: ${{ github.run_id }}
          token: ${{ secrets.GITHUB_TOKEN }}
