---
##############################
##############################
## Repository Visualization ##
##############################
##############################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

name: Repository Visualization
###########################################
# Start the job on all push or PR to main #
###########################################
on:
  schedule:
    # Sunday at 5:00pm
    - cron: "0 17 * * 0"

###############
# Set the Job #
###############
permissions:
  contents: read

jobs:
  build:
    # Name the Job
    name: Repository Visualization
    # Set the agent to run on
    runs-on: ubuntu-latest
    timeout-minutes: 60

    ###############
    # Steps below #
    ###############
    steps:
      ############################
      # Checkout the source code #
      ############################
      - name: Checkout Code
        uses: actions/checkout@v3

      ##############################
      # Create Visualization Files #
      ##############################
      - name: Create Visualization
        uses: githubocto/repo-visualizer@0.8.2
        with:
          output_file: "./diagram.svg"
          should_push: false

      ###########################
      # Configure the AWS creds #
      ###########################
      - name: Configure AWS Credentials
        if: success()
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      ############################
      # Push the image to aws s3 #
      ############################
