---
#############################
#############################
## Security run Trivy Scan ##
#############################
#############################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

#######################################
# Start the job on all push to master #
#######################################
# on:
#   push:
#     branches:
#       - 'master'
on:
  push:
    branches-ignore: [master]
  pull_request:
    branches-ignore: []

###############
# Set the Job #
###############
jobs:
  build:
    # Name the Job
    name: Security Scan - Trivy
    # Set the agent to run on
    runs-on: ubuntu-latest
    # Only run this on the main repo
    if: github.repository == 'github/super-linter'
    ##################
    # Load all steps #
    ##################
    steps:
      ##########################
      # Checkout the code base #
      ##########################
      - name: Checkout Code
        uses: actions/checkout@v2.3.4

      ##################
      # Download Trivy #
      ##################
      - name: Download and Install Trivy
        shell: bash
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/install.sh | sh -s -- -b /usr/local/bin
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/master/contrib/sarif.tpl -o sarif.tpl

      #################################
      # Run Trivy Scan of source code #
      #################################
      - name: Trivy Scan
        shell: bash
        run: trivy fs --format template --template @${GITHUB_WORKSPACE}/sarif.tpl -o report.sarif ${GITHUB_WORKSPACE}

      ################################
      # Upload report to secrity tab #
      ################################
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: 'report.sarif'
