# Disabling trivy scans while they get troubleshooting for failures
---
name: Trivy Container Scan
on:
  push:
    branches:
      - main
  pull_request:
  merge_group:

permissions:
  contents: read

jobs:
  scan-container:
    permissions:
      contents: read  # for actions/checkout to fetch code
      security-events: write  # for github/codeql-action/upload-sarif to upload SARIF results
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      ######################
      # Checkout code base #
      ######################
      - name: Checkout code
        uses: actions/checkout@v4

      #################################
      # Run Trivy Scan of source code #
      #################################
      - name: Trivy Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'report.sarif'
          severity: 'HIGH,CRITICAL'

      #################################
      # Upload report to security tab #
      #################################
      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'report.sarif'
