---
#########################
#########################
## Version GitHub Tags ##
#########################
#########################

#
# Documentation:
# https://help.github.com/en/articles/workflow-syntax-for-github-actions
#

##########################
# Name of the action job #
##########################
name: GitHub Tag Update

#####################################################
# Run the job when a release is published or edited #
#####################################################
on:
  release:
    types: [published, edited]

#################
# Start the job #
#################
permissions:
  contents: read

jobs:
  actions-tagger:
    permissions:
      contents: write  # for Actions-R-Us/actions-tagger to create a release and add latest tag
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      #############################
      # Check out the latest code #
      #############################
      - uses: actions/checkout@v3

      ######################
      # Run the tag action #
      ######################
      - uses: Actions-R-Us/actions-tagger@v2.0.2
        with:
          publish_latest_tag: true
        env:
          GITHUB_TOKEN: "${{secrets.GITHUB_TOKEN}}"
